spring:
  datasource:
    username: root
    password: yuxinxin
    url: jdbc:mysql://hadoop102:3306/uploadfile?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
shiro:
  loginUrl: /login.html
  sessionManager:
  # disable URL session rewriting
    sessionIdUrlRewritingEnabled: false
logging:
  level:
    com:
      competitive:
        dao=debug: